models/ctacteprov.py
from utils.db import db


class CtaCteProv(db.Model):
    __tablename__ = 'cta_cte_prov'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    idproveedor = db.Column(db.Integer, db.ForeignKey('proveedores.id'), nullable=False)
    fecha = db.Column(db.Date, nullable = False)
    debe = db.Column(db.Numeric(20,6), nullable = False)
    haber = db.Column(db.Numeric(20,6), nullable = False)
    idfactura = db.Column(db.Integer, db.ForeignKey('facturac.id'), nullable=False)
    
    def __init__(self, idproveedor, idfactura, fecha, debe, haber):
        self.idproveedor = idproveedor
        self.idfactura = idfactura
        self.fecha = fecha
        self.debe = debe
        self.haber = haber

routes/ctacteprov.py
from flask import Blueprint, render_template, request, redirect, flash, url_for, g
from sqlalchemy import func
from datetime import datetime
from utils.utils import format_currency
from models.proveedores import Proveedores
from models.ctacteprov import CtaCteProv
from services.ctacteprov import saldo_ctacte, getSaldosCtacteProv
from utils.db import db
from utils.utils import check_session
from utils.msg_alertas import alertas_mensajes

bp_ctacteprov = Blueprint('ctacteprov', __name__, template_folder='../templates/ctacteprov')

@bp_ctacteprov.route('/addCtaCteProv', methods = ['POST','GET'])
@check_session
def add_cta_cte_prov():
    if request.method == 'POST':
        idproveedor = request.form['idproveedor']
        fecha = request.form['fecha']
        importe = request.form['importe']
        debe_haber = request.form.get('debe_haber')
        try:
            if debe_haber == 'debe':
                debe = importe
                haber = 0
            else:
                debe = 0
                haber = importe
            ctacteprov = CtaCteProv(idproveedor, fecha, debe, haber)
            db.session.add(ctacteprov)
            db.session.commit()
            flash('Movimiento de cta cte grabado')
            return redirect(url_for('ctacteprov.lst_cta_cte_prov', id=idproveedor))
        except Exception as e:
            db.session.rollback()
            flash(f'Error grabado ctacte: {e}')
            return redirect(url_for('ctacteprov.lst_cta_cte_prov', id=idproveedor))
    
    if request.method == 'GET':
        return render_template('ctacte-prov.html', alertas=g.alertas, cantidadAlertas=g.cantidadAlertas, mensajes=g.mensajes, cantidadMensajes=g.cantidadMensajes)

@bp_ctacteprov.route('/lstctacteprov/<id>)')
@check_session
@alertas_mensajes
def lst_cta_cte_prov(id):
    proveedor = Proveedores.query.get_or_404(id)
    movimientos = CtaCteProv.query.filter_by(idproveedor=proveedor.id).all()
    saldo_total = saldo_ctacte(proveedor.id)
    saldoTotal = saldo_total['total_debe'] - saldo_total['total_haber']
    return render_template('lst-ctacteprov.html', movimientos=movimientos, idProveedor=proveedor.id, nomProveedor=proveedor.nombre, saldoTotal=saldoTotal, alertas=g.alertas, cantidadAlertas=g.cantidadAlertas, mensajes=g.mensajes, cantidadMensajes=g.cantidadMensajes)

@bp_ctacteprov.route('/saldosprov', methods=['GET', 'POST'])
@check_session
@alertas_mensajes
def saldosprov():
    if request.method == 'GET':
        # Obtener la fecha del formulario
        fecha_str = request.args.get('fecha')
        if fecha_str is None:
            # Si no se proporciona una fecha, usar la fecha actual
            fecha_str = datetime.now().strftime('%Y-%m-%d')
        # Convertir la fecha a un objeto datetime
        fecha = datetime.strptime(fecha_str, '%Y-%m-%d')
        
        # Realizar la consulta agregada
        saldos = getSaldosCtacteProv()

        # Pasar los resultados a la plantilla
        return render_template('saldos-ctacteprov.html', saldos=saldos, desde=fecha_str, alertas=g.alertas, cantidadAlertas=g.cantidadAlertas, mensajes=g.mensajes, cantidadMensajes=g.cantidadMensajes)
    else:
        fecha_str = request.form['fecha']
        return redirect(url_for('ctacteprov.saldosprov', fecha=fecha_str))

templates/ctacteprov/partials/_ctacte-prov.html
        <div class="card">
            <div class="card-body">
                <h3>Ingreso de movimiento en cta cte</h3>
                <form action="{{ url_for('ctacteprov.add_cta_cte_prov') }}" id="movCtaCte" method="post">
                    <div class="row">
                        <div class="mb-3 col-2"> 
                            <label for="idproveedor">#Proveedor</label>
                            <input class="form-control" type="text" name="idproveedor" id="idproveedor" readonly value="{{ idProveedor }}">
                        </div>
                        <div class="mb-3 col-10">
                            <label for="nombre">Nombre</label>
                            <input class="form-control" type="text" name="nombre" id="nombre" readonly value="{{ nomProveedor }}">   
                        </div>
                    </div>    
                    <div class="mb-3 col-4">
                        <label for="fecha">Fecha</label>
                        <input class="form-control" type="date" name="fecha" id="fecha" placeholder="Fecha del movimiento">
                    </div>    
                    <div class="m-3">
                        <hr>
                        <h6 class="ml-3">Tipo de ingreso</h6>
                        <hr>
                        <div class="row m-3">
                            <div class="form-check col-6">
                                <input class="form-check-input" type="radio" name="debe_haber" id="debe" value="debe">
                                <label class="form-check-label" for="flexRadioDefault1">
                                Debe
                                </label>
                            </div>
                            <div class="form-check col-6">
                                <input class="form-check-input" type="radio" name="debe_haber" id="haber" value="haber">
                                <label class="form-check-label" for="flexRadioDefault2">
                                Haber
                                </label>
                            </div>
                        </div>    
                        <hr>
                    </div>  
                    <div class="mb-3 col-6">
                        <label for="importe">Importe</label>
                        <input class="form-control" type="text" name="importe" id="importe" step="0.01" min="1" placeholder="Importe el monto">
                    </div>    

                    <button class="btn btn-exito" type="submit">Grabar movimiento</button>
                </form>
            </div>    
        </div>   