models/proveedores.py
from utils.db import db

class Proveedores(db.Model):
    __tablename__ = 'proveedores'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    nombre = db.Column(db.String(80))
    fantasia = db.Column(db.String(80))
    email = db.Column(db.String(100))
    telefono  = db.Column(db.String(20))
    documento = db.Column(db.String(13))
    direccion = db.Column(db.String(80))
    id_tipo_doc = db.Column(db.Integer, db.ForeignKey('tipo_doc.id'))
    id_tipo_iva = db.Column(db.Integer, db.ForeignKey('tipo_iva.id'))

    def __init__(self, nombre, fantasia, email, telefono, documento, direccion, tipo_doc, tipo_iva):
        self.nombre = nombre
        self.fantasia = fantasia
        self.email = email
        self.telefono = telefono
        self.documento = documento
        self.direccion = direccion
        self.id_tipo_doc = tipo_doc
        self.id_tipo_iva = tipo_iva

class FacturaC(db.Model):
    __tablename__ = 'facturac'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    idproveedor = db.Column(db.Integer, db.ForeignKey('proveedores.id'), nullable=False)
    fecha = db.Column(db.Date, nullable=False)
    periodo = db.Column(db.Date, nullable=False)
    total = db.Column(db.Numeric(20,6), nullable=False)
    iva = db.Column(db.Numeric(20,6), nullable=False)
    exento = db.Column(db.Numeric(20,6), nullable=False)
    impint = db.Column(db.Numeric(20,6), nullable=False)
    idsucursal = db.Column(db.Integer, db.ForeignKey('sucursales.id'))
    idtipocomprobante = db.Column(db.Integer, db.ForeignKey('tipo_comprobantes.id'))
    idusuario = db.Column(db.Integer, db.ForeignKey('usuarios.id'))
    idplancuenta = db.Column(db.Integer, db.ForeignKey('plan_ctas.id'))
    nro_comprobante = db.Column(db.String(13), nullable=False)
    usuario = db.relationship('Usuarios', backref=db.backref('facturac', lazy=True))
    proveedor = db.relationship('Proveedores', backref=db.backref('facturac', lazy=True))
    pagosfc = db.relationship('PagosFC', backref=db.backref('facturac', lazy=True))
    
    def __init__(self, idproveedor, fecha, periodo, total, nro_comprobante, iva=0, exento=0, impint=0, idsucursal=0, idtipocomprobante=0, idusuario=0, idplancuenta=0):
        self.idproveedor = idproveedor
        self.fecha = fecha
        self.periodo = periodo
        self.total = total
        self.nro_comprobante = nro_comprobante
        self.iva = iva
        self.exento = exento    
        self.impint = impint
        self.idsucursal = idsucursal
        self.idtipocomprobante = idtipocomprobante
        self.idusuario = idusuario
        self.idplancuenta = idplancuenta
        
class ItemC(db.Model):
    __tablename__ = 'itemsc'
    idfactura = db.Column(db.Integer, db.ForeignKey('facturac.id'), primary_key=True)
    id = db.Column(db.Integer, primary_key=True)
    idarticulo = db.Column(db.Integer, db.ForeignKey('articulos.id'), nullable=False)
    cantidad = db.Column(db.Numeric(20,6), nullable=False)
    precio_unitario = db.Column(db.Numeric(20,6), nullable=False)
    precio_total = db.Column(db.Numeric(20,6), nullable=False)
    iva = db.Column(db.Numeric(20,6), nullable=False)
    idalciva = db.Column(db.Integer, db.ForeignKey('alc_iva.id'), nullable=False)   
    exento = db.Column(db.Numeric(20,6), nullable=False)
    impint = db.Column(db.Numeric(20,6), nullable=False)
    articulo = db.relationship('Articulo', backref=db.backref('itemsc', lazy=True))
    factura = db.relationship('FacturaC', backref=db.backref('itemsc', lazy=True))
    
    def __init__(self, idfactura, id, idarticulo, cantidad, precio_unitario, precio_total, iva=0, idalciva=0, exento=0, impint=0):
        self.idfactura = idfactura
        self.id = id
        self.idarticulo = idarticulo
        self.cantidad = cantidad
        self.precio_unitario = precio_unitario    
        self.precio_total = precio_total
        self.iva = iva
        self.idalciva = idalciva
        self.exento = exento
        self.impint = impint

class ItemsOP(db.Model):
    __tablename__ = 'items_op'
    idop = db.Column(db.Integer, db.ForeignKey('facturac.id'), primary_key=True)
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    idfactura = db.Column(db.Integer, db.ForeignKey('facturac.id'))
    pago = db.Column(db.Numeric(20,6), nullable=False)
    
    def __init__(self, idop, idfactura, pago):
        self.idop = idop
        self.idfactura = idfactura
        self.pago = pago
        
class PagosFC(db.Model):
    __tablename__ = 'pagos_fc'
    idfactura = db.Column(db.Integer, db.ForeignKey('facturac.id'), primary_key=True)
    idpago = db.Column(db.Integer, primary_key=True)
    tipo  = db.Column(db.Integer, nullable=False)
    total = db.Column(db.Numeric(20,6), nullable=False)
    
    def __init__(self, idfactura, idpago, tipo, total):
        self.idfactura = idfactura
        self.idpago = idpago
        self.tipo = tipo
        self.total = total

class RemitoFacturas(db.Model):
    __tablename__ = 'remito_facturas'
    idremito = db.Column(db.Integer, db.ForeignKey('facturac.id'), primary_key=True)
    idfactura = db.Column(db.Integer, db.ForeignKey('facturac.id'), primary_key=True)
    
    
    def __init__(self, idremito, idfactura):
        self.idremito = idremito
        self.idfactura = idfactura

routes/proveedores.py
from flask import Blueprint, render_template, request, redirect, flash, url_for, jsonify, session, g
from datetime import date
from models.proveedores import Proveedores, FacturaC, RemitoFacturas
from models.configs import TipoDocumento, TipoIva, TipoComprobantes, PlanCtas, TipoCompAplica
from models.ctacteprov import CtaCteProv
from services.bancos import BancoService
from services.proveedores import procesar_nueva_compra, procesar_nuevo_gasto, get_factura, actualizar_precios_por_compras, \
    procesar_nuevo_remito, get_remito, procesar_nueva_op, get_movs_pendientes_ctacte, get_ordenes_pago
from utils.utils import check_session
from utils.msg_alertas import alertas_mensajes
from utils.db import db
from sqlalchemy.orm import aliased
from sqlalchemy import and_

bp_proveedores = Blueprint('proveedores', __name__, template_folder='../templates/proveedores')

#------------------ proveedores --------------

@bp_proveedores.route('/proveedores/<id>', methods=['GET'])
@check_session
@alertas_mensajes
def proveedores(id):
    print(request.method)
    tipo_docs = TipoDocumento.query.all()
    tipo_ivas = TipoIva.query.all()
    proveedores = Proveedores.query.all()
    proveedor = []  
    if id != 0:
        proveedor = Proveedores.query.get(id)
    return render_template('proveedores.html', proveedor=proveedor, tipo_docs=tipo_docs, tipo_ivas=tipo_ivas, proveedores=proveedores, alertas=g.alertas, cantidadAlertas=g.cantidadAlertas, mensajes=g.mensajes, cantidadMensajes=g.cantidadMensajes)

@bp_proveedores.route('/add_proveedor', methods=['GET', 'POST'])
@check_session
@alertas_mensajes
def add_proveedor():
    id = request.form['id']
    if id:
        proveedor = Proveedores.query.get(id)
        proveedor.nombre = request.form['nombre']
        proveedor.fantasia = request.form['fantasia']
        proveedor.direccion = request.form['direccion']
        proveedor.email = request.form['mail']
        proveedor.telefono = request.form['telefono']
        proveedor.documento = request.form['documento']
        proveedor.id_tipo_doc = request.form['tipoDoc']
        proveedor.id_tipo_iva = request.form['tipoIva']
        db.session.commit()
        flash('Proveedor actualizado')
    else:      
        nombre = request.form['nombre']
        fantasia = request.form['fantasia']
        direccion = request.form['direccion']
        mail = request.form['mail']
        telefono = request.form['telefono']
        documento = request.form['documento']
        tipo_doc = request.form['tipoDoc']
        tipo_iva = request.form['tipoIva']
        proveedores = Proveedores(nombre, fantasia=fantasia, email=mail, telefono=telefono, documento=documento, direccion=direccion, tipo_doc=tipo_doc, tipo_iva=tipo_iva)
        db.session.add(proveedores)
        db.session.commit()
        flash('Proveedor agregado')
    return redirect(url_for('proveedores.proveedores', id=0))

@bp_proveedores.route('/proveedor/<id>')
@check_session
def proveedor(id):
    proveedor = Proveedores.query.get(id)
    if proveedor:
        return jsonify(success=True, proveedor={"id": proveedor.id, "nombre": proveedor.nombre})
    else:
        return jsonify(success=False)

@bp_proveedores.route('/get_proveedor/<id>')
@check_session
def get_proveedor(id):
    proveedor = db.session.query(
        Proveedores.id.label('id'),
        Proveedores.nombre.label('nombre'),
        Proveedores.documento.label('documento'),
        Proveedores.email.label('email'),
        Proveedores.telefono.label('telefono'),
        Proveedores.id_tipo_doc.label('id_tipo_doc'),
        Proveedores.id_tipo_iva.label('id_tipo_iva')) \
        .filter(Proveedores.id == id).first()
    if proveedor:
        return jsonify(success=True, proveedor={'id': proveedor.id, 'nombre': proveedor.nombre, 'telefono': proveedor.telefono, 'tipo_doc':proveedor.id_tipo_doc, 'tipo_iva':proveedor.id_tipo_iva}) 
    else:
        return jsonify(success=False)

@bp_proveedores.route('/get_proveedores')
@check_session
def get_proveedores():
    nombre = request.args.get('nombre', '')
    if nombre:
        proveedores = db.session.query(
        Proveedores.id.label('id'),
        Proveedores.nombre.label('nombre'),
        Proveedores.documento.label('documento'),
        Proveedores.email.label('email'),
        Proveedores.telefono.label('telefono'),
        Proveedores.direccion.label('direccion'),
        Proveedores.id_tipo_doc.label('id_tipo_doc'),
        Proveedores.id_tipo_iva.label('id_tipo_iva'))\
        .filter(Proveedores.nombre.like(f"{nombre}%")).all()
    else:
        proveedores = []
    return jsonify([{'id': p.id, 'nombre': p.nombre, 'telefono': p.telefono, 'tipo_doc':p.id_tipo_doc, 'tipo_iva':p.id_tipo_iva} for p in proveedores]) 

@bp_proveedores.route('/delete_proveedor/<id>')
@check_session
def delete_proveedor(id):
    proveedor = Proveedores.query.get(id)
    db.session.delete(proveedor)
    db.session.commit()
    flash('Proveedor eliminado')
    return redirect(url_for('home'))

# ----------------- compras ------------------
@bp_proveedores.route('/compras', methods=['GET', 'POST'])
@check_session
@alertas_mensajes
def compras():
    if request.method == 'POST':
        desde = request.form['desde']
        hasta = request.form['hasta']
        return redirect(url_for('proveedores.compras', desde=desde, hasta=hasta))
    if request.method == 'GET':
        desde = request.args.get('desde')
        hasta = request.args.get('hasta')
        if desde == None:
            desde = date.today()
        if hasta == None:    
            hasta = date.today()
        facturas = db.session.query(FacturaC.id,
                                    FacturaC.fecha,
                                    FacturaC.nro_comprobante,
                                    FacturaC.total,
                                    TipoComprobantes.nombre.label('tipo_comprobante'),
                                    Proveedores.nombre.label('proveedor')) \
                                    .join(Proveedores, FacturaC.idproveedor == Proveedores.id) \
                                    .join(TipoComprobantes, FacturaC.idtipocomprobante == TipoComprobantes.id) \
                                    .filter(FacturaC.fecha >= desde, FacturaC.fecha <= hasta, FacturaC.idtipocomprobante != 11) \
                                    .order_by(FacturaC.fecha.desc()).all()
        return render_template('compras.html', facturas=facturas, desde=desde, hasta=hasta, alertas=g.alertas, cantidadAlertas=g.cantidadAlertas, mensajes=g.mensajes, cantidadMensajes=g.cantidadMensajes)
    
@bp_proveedores.route('/nueva_compra', methods=['GET', 'POST'])
@check_session
@alertas_mensajes
def nueva_compra():
    if request.method == 'POST':
        try:
            actualizoCostos = procesar_nueva_compra(request.form, session['id_sucursal'])
            flash('Factura grabada exitosamente')
            if actualizoCostos:
                flash('Se actualizaron los costos de los artículos')
            return redirect(url_for('index'))
        except Exception as e:
            flash(f'Ocurrió un error al procesar la compra: {e}')
            return redirect(url_for('proveedores.nueva_compra'))
    planesCtas = PlanCtas.query.all()  
    tiposComp = db.session.query(TipoComprobantes.id,
                                TipoComprobantes.nombre) \
                                .join(TipoCompAplica, and_(TipoComprobantes.id == TipoCompAplica.id_tipo_comp,  TipoCompAplica.id_tipo_oper == 2)).all()  
    hoy = date.today()
    return render_template('nueva_compra.html', hoy=hoy, planesCtas=planesCtas, tiposComp=tiposComp, alertas=g.alertas, cantidadAlertas=g.cantidadAlertas, mensajes=g.mensajes, cantidadMensajes=g.cantidadMensajes)

@bp_proveedores.route('/nuevo_gasto', methods=['GET', 'POST'])
@check_session
@alertas_mensajes
def nuevo_gasto():
    if request.method == 'POST':
        procesar_nuevo_gasto(request.form, session['id_sucursal']) 
        flash('Gasto grabado')
        return redirect(url_for('index'))
    else:
        planesCtas = PlanCtas.query.all()
        tiposComp = db.session.query(TipoComprobantes.id,
                                TipoComprobantes.nombre) \
                                .join(TipoCompAplica, and_(TipoComprobantes.id == TipoCompAplica.id_tipo_comp,  TipoCompAplica.id_tipo_oper == 2)).all()
        return render_template('nuevo_gasto.html', planesCtas=planesCtas, tiposComp=tiposComp, alertas=g.alertas, cantidadAlertas=g.cantidadAlertas, mensajes=g.mensajes, cantidadMensajes=g.cantidadMensajes)
    
@bp_proveedores.route('/ver_factura_comp/<id>') 
@check_session
@alertas_mensajes
def ver_factura_comp(id):
    factura, items, pagos = get_factura(id)
    return render_template('factura-comp.html', factura=factura, items=items, pagos=pagos, alertas=g.alertas, cantidadAlertas=g.cantidadAlertas, mensajes=g.mensajes, cantidadMensajes=g.cantidadMensajes)
        
@bp_proveedores.route('/actualizar_precios_porcompras/<id>') 
@check_session
def actualizar_precios_porcompras(id):
    try:
        actualizar_precios_por_compras(id)
        flash('Precios actualizados')
        return redirect(url_for('proveedores.ver_factura_comp', id=id))
    except Exception as e:
        flash(str(e), 'error')
        return redirect(url_for('proveedores.ver_factura_comp', id=id))

@bp_proveedores.route('/get_remitos/<int:idproveedor>')
@check_session
def get_remitos(idproveedor):
    if idproveedor > 0:
        remitos = db.session.query(FacturaC.id,
                                   FacturaC.fecha,
                                   FacturaC.nro_comprobante)\
                            .outerjoin(RemitoFacturas, RemitoFacturas.idremito == FacturaC.id) \
                            .filter(and_(FacturaC.idproveedor == idproveedor, FacturaC.idtipocomprobante == 11, RemitoFacturas.idremito == None)) \
                            .all()
    else:
        remitos = []
    

templates/proveedores/compras.html
{% extends "base.html" %}

{% block body %}
    <h2 class="m-3">Facturas de compra</h2>
    <div class="m-3">
        <a href="{{ url_for('proveedores.nueva_compra') }}" class="btn btn-primario">Nueva compra</a>
    </div>    

    <div class="row justify-content-center align-items-center">
        <div class="col-8">
            <div class="card m-3">
                <h5 class="px-5 pt-2">Periodo</h5>
                <div class="card-body">
                    <form action="" method="post">
                        <div class="row justify-content-md-center">
                            <div class="col-md-3">
                                <label for="desde">Desde</label>
                                <input type="date" name="desde" id="desde" class="form-control" value="{{ desde }}">
                            </div>
                            <div class="col-md-3">
                                <label for="hasta">Hasta</label>
                                <input type="date" name="hasta" id="hasta" class="form-control" value="{{ hasta }}">
                            </div>    
                            <div class="col-md-2 m-4">
                                <button type="submit" class="btn btn-primario">Buscar</button>
                            </div>    
                        </div>
                    </form>
                </div>    
            </div>
        </div>    
    </div>
    
    <div class="row justify-content-center align-items-center">
        <div class="col-8">
            <div class="table-responsive m-3" >
                <table class="table table-striped table-hover table-borderless align-middle" >
                    <thead class="table-light">
                        <caption>
                            Facturas de compra
                        </caption>
                        <tr>
                            <th>Proveedor</th>
                            <th>Tipo</th>
                            <th>Comprobante</th>
                            <th>Fecha</th>
                            <th>Total</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody class="table-group-divider">
                        {% for factura in facturas %}        
                            <tr class="table-dark">
                                <td scope="row">{{ factura.proveedor}}</td>
                                <td>{{ factura.tipo_comprobante }}</td>
                                <td>{{ factura.nro_comprobante }}</td>
                                <td>{{ factura.fecha.strftime('%d-%m-%Y') }}</td>
                                <td style="text-align:center">{{ "${:,.2f}".format(factura.total) }}</td>
                                <td><a href="{{ url_for('proveedores.ver_factura_comp', id=factura.id) }}" class="btn btn-primario">Ver</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>
                        
                    </tfoot>
                </table>
            </div>
        </div>    
    </div>


{% endblock %}

templates/proveedores/factura-comp.html
{% extends "base.html" %}


{% block body %}
<h3 class="m-3">Comprobante de compra</h3>

<div class="m-3 card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Factura de compras</h6>
    </div>
    <div class="card-body">
        <div class='input-group mb-3'>
            <div class="card-body">
                <div class="row">
                    <div class="col-2">
                        <label for="id">#id</label>
                        <input type="number" class="form-control" name="id" id="id" value="{{ factura.id }}" readonly>
                    </div>
                    <div class="col-5">
                        <label for="cliente">Proveedor</label>
                        <input type="text" class="form-control" name="cliente" id="cliente" value="{{ factura.nombre }}">
                    </div>    
                    <div class="col-2">
                        <label for="fecha">Fecha</label>
                        <input type="date" class="form-control" name="fecha" id="fecha" value="{{ factura.fecha }}">
                    </div>        
                    <div class="col-2">
                        <label for="periodo">Periodo {{ factura.periodo }}</label>
                        <input type="month" class="form-control" name="periodo" id="periodo" value="{{ factura.periodo }}">
                    </div>                
                </div>
                <div class="row">
                    <div class="col-3">
                        <label for="total">Total</label>
                        <input type="number" class="form-control precio-normal" name="total" id="total" step="0.01" value="{{ factura.total|round(2) }}">
                    </div>    
                    <div class="col-3">
                        <label for="iva">IVA</label>
                        <input type="number" class="form-control precio-normal" name="iva" id="iva" step="0.01" value="{{ factura.iva|round(2) }}">
                    </div>    
                    <div class="col-3">
                        <label for="exento">Exento</label>
                        <input type="number" class="form-control precio-normal" name="exento" id="exento" step="0.01" value="{{ factura.exento|round(2) }}">
                    </div>    
                    <div class="col-3">
                        <label for="impint">Imp. int.</label>
                        <input type="number" class="form-control precio-normal" name="impint" id="impint" step="0.01" value="{{ factura.impint|round(2) }}">   
                    </div>    
                </div>    
            </div>    
        </div>

        <div class="m-3 card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Artículos facturados</h6>
            </div>
            <div class="card-body">

                <div class="table-responsive">
                    <table class="table table-striped table-hover table-borderless table-dark align-middle">
                        <thead class="table-light">
                            <caption>
                                Artículos
                            </caption>
                            <tr>
                                <th>Código</th>
                                <th>Detalle</th>
                                <th>Cantiad</th>
                                <th>Precio U.</th>
                                <th>Precio F.</th>
                                <th>Iva</th>
                            </tr>
                        </thead>
                        <tbody class="table-group-divider">
                            {% for item in items %}    
                                <tr class="table-light">
                                    <td scope="row">{{ item.codigo }}</td>
                                    <td>{{ item.detalle }}</td>
                                    <td>{{ item.cantidad|round(2) }}</td>
                                    <td>{{ item.precio_unitario|round(2) }}</td>
                                    <td>{{ item.precio_total|round(2) }}</td>
                                    <td>{{ item.iva|round(2) }}</td>
                                </tr>
                                {% endfor %}    
                        </tbody>
                        <tfoot>
                            
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>

        <div class="m-3 card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Formas de pago</h6>
            </div>
            <div class="card-body">
                {% for pago in pagos %}
                <div class="row">
                    <div class="col-3">
                        <label for="forma_pago">Forma de pago</label>
                        <input type="text" class="form-control" name="forma_pago" id="forma_pago" value="{{ pago.pagos_cobros }}">
                    </div>
                    <div class="col-3">
                        <label for="total_pago">Importe del pago</label>
                        <input type="number" class="form-control precio-destacado" name="total_pago" id="total_pago" step="0.01" value="{{ pago.total|round(2) }}">
                    </div>
                </div>    
                {% endfor %}
            </div>
        </div>

        <a href="{{ url_for('proveedores.actualizar_precios_porcompras', id=factura.id) }}" class="btn btn-success"> Actualizar precios </a>
    </div>



{% endblock %}

templates/proveedores/proveedores.html
{% extends 'base.html'%}
{% block body %}
    <div class="m-2">
        <div class="row justify-content-center align-items-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-body">
                        <h3>Ingreso de Proveedores</h3>
                        <form action="{{ url_for('proveedores.add_proveedor') }}" method="POST">
                        
                            <div class="row">
                                <div class="mb-3 col-1"> 
                                    <label for="id">#Id</label>
                                    <input class="form-control" type="text" name="id" id="id" placeholder="Ingrese el ID" value="{{ proveedor.id }}" readonly>
                                </div>
                                <div class="mb-3 col-5"> 
                                    <label for="nombre">Nombre/Razón Social</label>
                                    <input class="form-control" type="text" name="nombre" id="nombre" placeholder="Ingrese el nombre" value="{{ proveedor.nombre }}" required>
                                </div>
                                <div class="mb-3 col-5"> 
                                    <label for="fantasia">Nombre de fantasía</label>
                                    <input class="form-control" type="text" name="fantasia" id="fantasia" placeholder="Ingrese la fantasia" value="{{ proveedor.fantasia }}" required>
                                </div>
                            </div>  
                            <div class="row">
                                <div class="mb-3 col-5">
                                    <label for="direccion">Dirección</label>
                                    <input class="form-control" type="text" name="direccion" id="direccion" placeholder="Ingrese la dirección" value="{{ proveedor.direccion }}">
                                </div>    
                                <div class="mb-3 col-5">
                                    <label for="mail">E-mail</label>
                                    <input class="form-control" type="text" name="mail" id="mail" placeholder="Ingrese el mail" value="{{ proveedor.email }}">
                                </div>    
                            </div>  
                            <div class="row">
                                <div class="mb-3 col-3">
                                    <label for="documento">Documento/CUIT/CUIL</label>
                                    <input class="form-control" type="text" name="documento" id="documento" placeholder="Ingrese el n° de documento/CUIL/CUIT" value="{{ proveedor.documento }}" required>
                                </div>    
                                
                                <div class="col-2 mb-3">
                                    <label for="tipoDoc">Tipo de Documento</label>
                                    <select class="form-control" name="tipoDoc" id="tipoDoc" required>
                                        {% for tipo in tipo_docs %}
                                            <option value="{{ tipo.id }}" {% if tipo.id == proveedor.id_tipo_doc %}selected{% endif %}>{{ tipo.nombre }}</option>
                                        {% endfor %}
                                        
                                    </select>    
                                    
                                </div>
                                <div class="col-2 mb-3">
                                    <label for="tipoIva">Tipo IVA</label>
                                    <select class="form-control" name="tipoIva" id="tipoIva" required>
                                        {% for tipo in tipo_ivas %}
                                            <option value="{{ tipo.id }}" {% if tipo.id == proveedor.id_tipo_iva %}selected{% endif %}>{{ tipo.descripcion }}</option>
                                        {% endfor %}
                                        
                                    </select>    
                                    
                                </div>
                                <div class="mb-3 col-3">
                                    <label for="telefono">Teléfono</label>
                                    <input class="form-control" type="text" name="telefono" id="telefono" placeholder="Ingrese el n° de teléfono" value="{{ proveedor.telefono }}">
                                </div>
                            </div>
                            <button class="btn btn-success" type="submit">Grabar</button>
                        </form>
                    </div>    
                </div>   
            </div>    
        </div>    
        <div class="row justify-content-center align-items-center">
            <div class="col-md-10">
                <h3 class="m-3">Proveedores</h3>
                <p class="m-3">Listado de proveedores registrados en el sistema.</p>
            </div>
              
            <div class="col-md-10">
                {% include 'partials/_lst-proveedores.html' %}
            </div>     
        </div>    
    </div>    

    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script src="{{ url_for('static', filename='js/dataTables.js')}}"></script>

{% endblock %}    