models/entidades_cred.py
from utils.db import db
from datetime import timedelta, date, datetime

class EntidadesCred(db.Model):
    __tablename__ = 'entidades'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    entidad = db.Column(db.String(200), nullable=False)
    telefono = db.Column(db.String(200), nullable=False)
    baja = db.Column(db.Date, nullable=False)
    
    def __init__(self, entidad, telefono):
        self.entidad = entidad
        self.telefono = telefono
        self.baja = datetime(1900, 1, 1)
        
class FinanciacionEntCred(db.Model):
    __tablename__ = 'financiacion_ent'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    id_entidad = db.Column(db.Integer, db.ForeignKey('entidades.id'), nullable=False)
    cuotas = db.Column(db.Integer, nullable=False)
    coeficiente = db.Column(db.Numeric(20, 6), nullable=False)
    acreditacion_dias = db.Column(db.Integer, nullable=False)

    def __init__(self, id_entidad, cuotas, coeficiente, acreditacion_dias):
        self.id_entidad = id_entidad
        self.cuotas = cuotas
        self.coeficiente = coeficiente
        self.acreditacion_dias = acreditacion_dias
        
class MovEntidades(db.Model):
    __tablename__ = 'mov_entidades'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    idfactura = db.Column(db.Integer, db.ForeignKey('facturav.id'), nullable=False)
    identidad = db.Column(db.Integer, db.ForeignKey('entidades.id'), nullable=False)
    cuotas = db.Column(db.Integer, nullable=False)
    total = db.Column(db.Numeric(20, 6), nullable=False)
    intereses = db.Column(db.Numeric(20, 6), nullable=False)
    documento = db.Column(db.String(20), nullable=False)
    telefono = db.Column(db.String(20), nullable=False)

    def __init__(self, idfactura, identidad, cuotas, total, intereses, documento, telefono):
        self.idfactura = idfactura
        self.identidad = identidad
        self.cuotas = cuotas
        self.total = total
        self.intereses = intereses
        self.documento = documento
        self.telefono = telefono

routes/entidades_cred.py
from flask import Blueprint, render_template, request, redirect, flash, url_for, g, jsonify
from models.entidades_cred import EntidadesCred
from models.ventas import Factura, PagosFV
from models.clientes import Clientes
from models.sucursales import Sucursales
from services.entidades_cred import getFinanciamiento, grabarAlicuotas, calcular_coeficiente
from utils.db import db
from utils.utils import check_session
from utils.msg_alertas import alertas_mensajes
from datetime import datetime

bp_entidades = Blueprint('entidades', __name__, template_folder='../templates/entidades')

@bp_entidades.route('/entidades/<id>', methods=['GET', 'POST'])
@bp_entidades.route('/entidades', methods=['GET', 'POST'])
@check_session
@alertas_mensajes
def entidades(id=0):
    entidades = EntidadesCred.query.all()
    if id != 0:
        entidad = EntidadesCred.query.get(id)
        if entidad:
            if request.method == 'POST':
                entidad.entidad = request.form['entidad']
                entidad.telefono = request.form['telefono']
                try:
                    db.session.commit()
                    flash('Entidad crediticia actualizada')
                    return redirect(url_for('entidades.entidades'))
                except Exception as e:
                    db.session.rollback()
                    flash(f'Error actualizando entidad crediticia: {e}')
                    return redirect(url_for('entidades.entidades'))
    else:    
        entidad = []
    return render_template('entidades-cred.html', entidades=entidades, entidad=entidad, alertas=g.alertas, cantidadAlertas=g.cantidadAlertas, mensajes=g.mensajes, cantidadMensajes=g.cantidadMensajes)

@bp_entidades.route('/add_entidad', methods = ['POST','GET'])
@check_session
@alertas_mensajes
def add_entidad():
    if request.method == 'POST':
        id = request.form['id']
        entidad = request.form['entidad']
        telefono = request.form['telefono']
        try:
            if id != 0:
                entidad = EntidadesCred.query.get(id)
                entidad.entidad = request.form['entidad']
                entidad.telefono = request.form['telefono']
            else:
                entidad = EntidadesCred(entidad, telefono)
                db.session.add(entidad)
            db.session.commit()
            flash('Entidad crediticia grabada')
            return redirect(url_for('entidades.entidades'))
        except Exception as e:
            db.session.rollback()
            flash(f'Error grabado entidad crediticia: {e}')
            return redirect(url_for('entidades.entidades'))
    
    if request.method == 'GET':
        return render_template('entidades-cred.html', alertas=g.alertas, cantidadAlertas=g.cantidadAlertas, mensajes=g.mensajes, cantidadMensajes=g.cantidadMensajes)
    
@bp_entidades.route('/listado_movimientos', methods=['GET', 'POST'])
@check_session
@alertas_mensajes
def listado_movimientos():
    entidades = EntidadesCred.query.all()
    if request.method == 'GET':
        desde = request.args.get('desde')
        hasta = request.args.get('hasta')
        if not desde:
            desde = datetime.now().strftime('%Y-%m-%d')
        if not hasta:
            hasta = datetime.now().strftime('%Y-%m-%d')
        entidad_id = request.args.get('idEntidad')
        if entidad_id != None:
            print(f'Entidades Cred: {entidad_id}')
            movimientos = db.session.query(Factura.id, 
                                        Factura.idcliente,
                                        Factura.nro_comprobante,
                                        Factura.fecha, 
                                        Factura.total, 
                                        Sucursales.nombre.label('sucursal'),
                                        Clientes.nombre.label('cliente'),
                                        PagosFV.total.label('pago_total'), 
                                        EntidadesCred.entidad) \
                                    .join(PagosFV, Factura.id == PagosFV.idfactura) \
                                    .join(EntidadesCred, PagosFV.entidad == EntidadesCred.id) \
                                    .join(Clientes, Factura.idcliente == Clientes.id) \
                                    .join(Sucursales, Factura.idsucursal == Sucursales.id) \
                                    .filter(Factura.fecha >= desde,
                                            Factura.fecha <= hasta,
                                            EntidadesCred.id == entidad_id).all()
        else:
            print(f'Sin Entidades Cred')
            movimientos = []
        return render_template('listado-movimientos.html', desde=desde, hasta=hasta, entidades=entidades, movimientos=movimientos, alertas=g.alertas, cantidadAlertas=g.cantidadAlertas, mensajes=g.mensajes, cantidadMensajes=g.cantidadMensajes)
    else:
        movimientos = []
        desde = request.form.get('desde', '')
        hasta = request.form.get('hasta', '')
        idEntidad = request.form.get('entidad', '')
        return redirect(url_for('entidades.listado_movimientos', desde=desde, hasta=hasta, idEntidad=idEntidad))

@bp_entidades.route('/alicuotas/<int:id>', methods=['GET', 'POST'])
@check_session
@alertas_mensajes
def alicuotas(id):
    if request.method == 'POST':
        resultado =grabarAlicuotas(id, request.form)
        if resultado:
            flash('Alícuotas grabadas correctamente')
        return redirect(url_for('entidades.alicuotas', id=id))
    else:
        entidad, financiamiento = getFinanciamiento(id)
        return render_template('fin-ent-cred.html', entidad=entidad, financiamiento=financiamiento, alertas=g.alertas, cantidadAlertas=g.cantidadAlertas, mensajes=g.mensajes, cantidadMensajes=g.cantidadMensajes)
        
@bp_entidades.route('/coeficiente_cuotas/<int:tarjeta>/<int:cuotas>', methods=['GET'])
def coeficiente_cuotas(tarjeta, cuotas):
    if request.method == 'GET':
        return jsonify({'coeficiente': calcular_coeficiente(tarjeta, cuotas)})

templates/entidades/entidades-cred.html
{% extends "base.html" %}

{% block body %}
<div class="m-3">
    <h3>Entidades de crédito</h3>
</div>
<div class="m-2">
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <h3>Ingreso de entidades</h3>
                    <form action="{{ url_for('entidades.add_entidad') }}" method="post">
                        <div class="row">
                            <div class="mb-3 col-2"> 
                                <label for="id"># Id</label>
                                <input class="form-control" type="text" name="id" id="id" readonly value="{{ entidad.id }}">
                            </div>    
                            <div class="mb-3 col-10"> 
                                <label for="entidad">Entidad</label>
                                <input class="form-control" type="text" name="entidad" id="entidad" placeholder="Ingrese el nombre de la entidad" value="{{ entidad.entidad }}">
                            </div>
                        </div>    
                        <div class="mb-3">
                            <label for="telefono">Teléfono</label>
                            <input class="form-control" type="text" name="telefono" id="detalle" placeholder="Ingrese el teléfono" value="{{ entidad.telefono }}">  
                        </div>    
                        
                        <button class="btn btn-success" type="submit">Grabar</button>
                    </form>
                </div>    
            </div>   
        </div>    
        
        <div class="col-8">
            {% include 'partials/_lst-entidades.html' %}
        </div>     
    </div>      
</div>    
{% endblock %}

templates/entidades/fin-ent-cred.html
{% extends "base.html" %}

{% block body %}
<div class="m-3">
    <h3>Alícuotas de cuotas</h3>
</div>
<div class="m-2">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h3>Ingreso de alícuoptas para </h3>
                    <form action="{{ url_for('entidades.alicuotas', id=entidad.id) }}" method="post">
                        <div class="row">
                            <div class="mb-3 col-2"> 
                                <label for="id"># Id</label>
                                <input class="form-control" type="text" name="id" id="id" readonly value="{{ entidad.id }}">
                            </div>    
                            <div class="mb-3 col-8"> 
                                <label for="entidad">Entidad</label>
                                <input class="form-control" type="text" name="entidad" id="entidad" placeholder="Ingrese el nombre de la entidad" readonly value="{{ entidad.entidad }}">
                            </div>
                        </div>
                        <div class="row">
                            <div class="mb-3 col-4">
                                
                                <a href="#" class="btn btn-secundario" id="agregarAlicuota">Agregar alícuota</a>
                            </div>
                        </div>    

                        <div class="row">
                            
                            <div class="table-responsive">
                                <table class="table table-dark" id="tabla-alicuotas" name="tabla-alicuotas">
                                    <thead>
                                        <tr>
                                            <th scope="col"># Id</th>
                                            <th scope="col">Cuotas</th>
                                            <th scope="col">Alícuota</th>
                                            <th scope="col">Días acred</th>
                                            <th scope="col">Acciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for alicuota in financiamiento %}
                                            <tr class="table table-light">
                                                <td scope="row">{{ alicuota.id }}</td>
                                                <td><input type="text" class="form-control alicuota-cuota" name="items[{{loop.index}}][cuota]" required value="{{ alicuota.cuotas }}" onfocus="this.select()"></td>
                                                <td><input type="number" class="form-control alicuota-alicuota" name="items[{{loop.index}}][alicuota]" step="0.001" required value="{{'{0:0.4f}'.format(alicuota.coeficiente)}}" onfocus="this.select()"></td>
                                                <td><input type="number" class="form-control alicuota-dias" name="items[{{loop.index}}][dias]" required value="{{ alicuota.acreditacion_dias }}" onfocus="this.select()"></td>
                                                <td><button type="button" class="btn btn-danger btn-eliminar">Eliminar</button></td>
                                            </tr>
                                        {% endfor %}    
                                        <script>
                                            contadorFilas = {{ financiamiento|length }};
                                        </script>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <button type="submit" class="mt-3 mb-3 btn btn-primario">Guardar alícuotas</button>
                    </form>
                </div>    
            </div>   
        </div>    
    </div>      
</div>    

<script>

// Agregar nueva fila
let contadorFilas = 0;
const tablaItems = document.querySelector("#tabla-alicuotas tbody");

document.getElementById("agregarAlicuota").addEventListener("click", () => {
  const nuevaFila = `
                <tr class="items">
                    <td class="id-alicuota" name="items[${contadorFilas}][idalicuota]"> ${contadorFilas} </td>
                    <td><input type="text" class="form-control alicuota-cuota" name="items[${contadorFilas}][cuota]" required onfocus="this.select()"></td>
                    <td><input type="number" class="form-control alicuota-alicuota" name="items[${contadorFilas}][alicuota]" step="0.001" onfocus="this.select()"></td>
                    <td><input type="number" class="form-control alicuota-dias" name="items[${contadorFilas}][dias]" required onfocus="this.select()"></td> 
                    <td><button type="button" class="btn btn-danger btn-eliminar">Eliminar</button></td>
                </tr>`;
  tablaItems.insertAdjacentHTML("beforeend", nuevaFila);
  contadorFilas++;
  // Enfocar el nuevo input de código
  const nuevoInputCuota = tablaItems.querySelector(`tr:last-child .alicuota-cuota`);
  nuevoInputCuota.focus();
});

// Eliminar fila
tablaItems.addEventListener("click", (itemDiv) => {
  if (itemDiv.target.classList.contains("btn-eliminar")) {
    itemDiv.target.closest("tr").remove();
  }
});


</script>
{% endblock %}

templates/entidades/listado-movimientos.html
{% extends "base.html" %}

{% block body %}
<div class="m-3">
    <h3>Listado de movimientos de entidades de crédito</h3>
</div>
<div class="m-2">
    <form action="{{ url_for('entidades.listado_movimientos') }}" method="post">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-2">
                        <label for="desde">Desde</label>
                        <input class="form-control" type="date" name="desde" id="desde" value="{{ desde }}" required>
                    </div>
                    <div class="col-2">
                        <label for="hasta">Hasta</label>
                        <input class="form-control" type="date" name="hasta" id="hasta" value="{{ hasta }}" required>
                    </div>
                    <div class="col-4">    
                        <label for="entidad">Entidad</label>
                        <select class="form-control" name="entidad" id="entidad" required>
                            <option value="">Seleccione una entidad</option>
                            {% for entidad in entidades %}
                                <option value="{{ entidad.id }}">{{ entidad.entidad }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="row mt-3">        
                    <div class="col-3">
                        <button class="btn btn-success" type="submit">Consultar</button>
                    </div>    
                </div>    
            </div>
        </div>
    </form>
    <div class="card mt-3">
        <div class="card-header">
            <h5>Movimientos</h5>
        </div>    
        <div class="mt-3">
            {% if movimientos %}
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Sucursal</th>
                            <th>Fecha</th>
                            <th>Cliente</th>
                            <th>N° comprobante</th>
                            <th>Total fac.</th>
                            <th>Total pago</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for movimiento in movimientos %}
                            <tr>
                                <td>{{ movimiento.sucursal }}</td>
                                <td>{{ movimiento.fecha }}</td>
                                <td>{{ movimiento.cliente }}</td>
                                <td>{{ movimiento.nro_comprobante }}</td>
                                <td>{{ "${:,.2f}".format(movimiento.total) }}</td>
                                <td>{{ "${:,.2f}".format(movimiento.pago_total) }}</td>
                                <td>
                                    <a class="btn btn-primary" href="{{ url_for('ventas.ver_factura_vta', id=movimiento.id) }}">Ver factura</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p class="ml-3">No se encontraron movimientos para los criterios seleccionados.</p>
            {% endif %}    
        </div>    
    </div>    
{% endblock %}