models/creditos.py
from utils.db import db
from datetime import date

# Planes de Créditos
class PlanesCreditos(db.Model):
    __tablename__ = 'planes_creditos'

    id = db.Column(db.Integer, primary_key=True)
    nombre = db.Column(db.String(100), nullable=False)
    descripcion = db.Column(db.String(500), nullable=False)
    tasa_interes = db.Column(db.Float, nullable=False)
    cuotas = db.Column(db.Integer, nullable=False)
    anticipo = db.Column(db.Boolean, default=False)
    garantes = db.Column(db.SmallInteger, default=1)
    baja = db.Column(db.Date, default=False)

    def __init__(self, nombre, descripcion, tasa_interes, cuotas, anticipo=False, garantes=1, baja=date(1900, 1, 1)):
        self.nombre = nombre
        self.descripcion = descripcion
        self.tasa_interes = tasa_interes
        self.cuotas = cuotas
        self.anticipo = anticipo
        self.garantes = garantes
        self.baja = baja

"""
#Definicion de Cuotas de los Planes de Créditos        
class PlanesCuotas(db.Model):
    __tablename__ = 'planes_cuotas'

    id = db.Column(db.Integer, primary_key=True)
    idplan = db.Column(db.Integer, db.ForeignKey('planes_creditos.id'), nullable=False)
    numero_cuota = db.Column(db.Integer, nullable=False)
    recargo_cuota = db.Column(db.Numeric(20, 6), nullable=False)

    def __init__(self, idplan, numero_cuota, recargo_cuota):
        self.idplan = idplan
        self.numero_cuota = numero_cuota
        self.recargo_cuota = recargo_cuota
"""

# Estados de Créditos
class EstadosCreditos(db.Model):
    __tablename__ = 'estados_creditos'

    id = db.Column(db.Integer, primary_key=True)
    nombre = db.Column(db.String(50), nullable=False)
    descripcion = db.Column(db.String(200), nullable=False)

    def __init__(self, nombre, descripcion):
        self.nombre = nombre
        self.descripcion = descripcion

#Categorias de clientes y planes de créditos
class CategoriasCreditos(db.Model):
    __tablename__ = 'categorias_creditos'
    idplan = db.Column(db.Integer, db.ForeignKey('planes_creditos.id'), primary_key=True)
    idcategoria = db.Column(db.Integer, db.ForeignKey('categorias.id'), primary_key=True)
    
    def __init__(self, idplan, idcategoria):
        self.idplan = idplan    
        self.idcategoria = idcategoria
    

# Créditos
class Creditos(db.Model):
    __tablename__ = 'creditos'

    id = db.Column(db.Integer, primary_key=True)
    idsucursal = db.Column(db.Integer, db.ForeignKey('sucursales.id'), nullable=False)
    idcliente = db.Column(db.Integer, db.ForeignKey('clientes.id'), nullable=False)
    idplan = db.Column(db.Integer, db.ForeignKey('planes_creditos.id'), nullable=False)
    cuotas = db.Column(db.Integer, nullable=False)
    monto_total = db.Column(db.Numeric(20, 6), nullable=False)
    estado = db.Column(db.Integer, db.ForeignKey('estados_creditos.id'), nullable=False)
    fecha_solicitud = db.Column(db.Date, nullable=False)
    fecha_inicio = db.Column(db.Date, nullable=False)
    fecha_fin = db.Column(db.Date, nullable=False)
    idfactura = db.Column(db.Integer, db.ForeignKey('facturav.id'), nullable=True)
    observaciones = db.Column(db.String(500), nullable=True) 

    def __init__(self, idsucursal, idcliente, idplan, cuotas, monto_total, estado, fecha_solicitud, fecha_inicio, fecha_fin, idfactura=None, observaciones=None):
        self.idsucursal = idsucursal
        self.idcliente = idcliente
        self.idplan = idplan
        self.cuotas = cuotas
        self.monto_total = monto_total
        self.estado = estado
        self.fecha_solicitud = fecha_solicitud
        self.fecha_inicio = fecha_inicio
        self.fecha_fin = fecha_fin
        self.idfactura = idfactura
        self.observaciones = observaciones
        
#Garantes de los Créditos
class GarantesCreditos(db.Model):
    __tablename__ = 'garantes_creditos'
    idcredito = db.Column(db.Integer, db.ForeignKey('creditos.id'), primary_key=True)
    idgarante = db.Column(db.Integer, db.ForeignKey('clientes.id'), primary_key=True)
    
    def __init__(self, idcredito, idgarante):
        self.idcredito = idcredito
        self.idgarante = idgarante
        
# Documentos requeridos para Créditos        
class DocumentosCreditos(db.Model):
    __tablename__ = 'documentos_creditos'

    id = db.Column(db.Integer, primary_key=True)
    nombre = db.Column(db.String(100), nullable=False)
    
    def __init__(self, nombre):
        self.nombre = nombre
    
# Relación entre Documentos y Créditos
# Esta tabla relaciona los documentos requeridos con los créditos específicos    
class DocumentosParaCreditos(db.Model):
    __tablename__ = 'planes_creditos_documentos'

    iddocumento_credito = db.Column(db.Integer, db.ForeignKey('documentos_creditos.id'), primary_key=True)
    idplan_credito = db.Column(db.Integer, db.ForeignKey('planes_creditos.id'), primary_key=True)

    def __init__(self, iddocumento_credito, idplan_credito):
        self.iddocumento_credito = iddocumento_credito
        self.idplan_credito = idplan_credito

# Documentos específicos de Créditos
# Esta tabla almacena los documentos específicos asociados a cada crédito
class DocumentosDelCreditos(db.Model):
    __tablename__ = 'documentos_del_creditos'

    id = db.Column(db.Integer, primary_key=True)
    idcredito = db.Column(db.Integer, db.ForeignKey('creditos.id'), nullable=False)
    iddocumento_credito = db.Column(db.Integer, db.ForeignKey('documentos_creditos.id'), nullable=False)
    documento = db.Column(db.String(255), nullable=False)

    def __init__(self, idcredito, iddocumento_credito, documento):
        self.idcredito = idcredito
        self.iddocumento_credito = iddocumento_credito
        self.documento = documento

# Vencimientos de las cuotas de los Créditos
class VencimientosCreditos(db.Model):
    __tablename__ = 'vencimientos_creditos'

    id = db.Column(db.Integer, primary_key=True)
    idcredito = db.Column(db.Integer, db.ForeignKey('creditos.id'), nullable=False)
    numero_cuota = db.Column(db.Integer, nullable=False)
    fecha_vencimiento = db.Column(db.Date, nullable=False)
    monto = db.Column(db.Numeric(20, 6), nullable=False)

    def __init__(self, idcredito,numero_cuota, fecha_vencimiento, monto):
        self.idcredito = idcredito
        self.numero_cuota = numero_cuota
        self.fecha_vencimiento = fecha_vencimiento
        self.monto = monto

# Pagos realizados en las cuotas de los Créditos
class PagosCreditos(db.Model):
    __tablename__ = 'pagos_creditos'

    id = db.Column(db.Integer, primary_key=True)
    idcredito = db.Column(db.Integer, db.ForeignKey('creditos.id'), nullable=False)
    idvencimiento = db.Column(db.Integer, db.ForeignKey('vencimientos_creditos.id'), nullable=False)
    idfactura = db.Column(db.Integer, db.ForeignKey('facturav.id'), nullable=True)
    fecha_pago = db.Column(db.Date, nullable=False)
    monto = db.Column(db.Numeric(20, 6), nullable=False)
    punitorios = db.Column(db.Numeric(20, 6), default=0.0)

    def __init__(self, idcredito, idvencimiento, idfactura, fecha_pago, monto, punitorios=0.0):
        self.idcredito = idcredito
        self.idvencimiento = idvencimiento
        self.idfactura = idfactura
        self.fecha_pago = fecha_pago
        self.monto = monto
        self.punitorios = punitorios

routes/creditos.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify, send_file
from flask import g
from utils.utils import check_session
from utils.msg_alertas import alertas_mensajes
from models.entidades_cred import EntidadesCred
from services.creditos import get_planes_creditos, procesar_plan_credito, get_documentos_creditos, \
                              procesar_documento_creditos, get_estados_creditos, procesar_estado_creditos, \
                              get_docs_por_plan, asignar_documento_para_plan, limpiar_documentos_para_plan, \
                              generar_cronograma_frances, get_requisitos, generar_credito_cliente, \
                              get_cats_por_plan, limpiar_categorias_para_plan, asignar_categoria_para_plan, \
                              get_planes_creditos_categoria, get_creditos_by_estado, get_credito_by_id,\
                              buscar_documento_descarga, grabar_cuotas, actualizar_credito,get_credito_by_idcliente, \
                              vencimientos_cuotas_creditos, get_cuotas_pendientes, generarRecibo
from datetime import date, timedelta


bp_creditos = Blueprint('creditos', __name__, template_folder='../templates/creditos')

@bp_creditos.route('/config_cred')
@check_session
@alertas_mensajes
def config_cred():
    planes_creditos = get_planes_creditos()
    documentos_de_creditos = get_documentos_creditos()
    estados = get_estados_creditos()
    documentos_por_plan = get_docs_por_plan()
    return render_template('config-cred.html', planes_creditos=planes_creditos, documentos_de_creditos=documentos_de_creditos, estados=estados, documentos_por_plan=documentos_por_plan, alertas=g.alertas, cantidadAlertas=g.cantidadAlertas, mensajes=g.mensajes, cantidadMensajes=g.cantidadMensajes)

@bp_creditos.route('/get_documentos_por_plan/<id>')
@check_session
def get_documentos_por_plan(id):
    documentos_por_plan = get_docs_por_plan(id)
    documentos = [{'idDoc': d.id, 'documento': d.nombre, 'idDocCred': d.iddocumento_credito, 'idPlanCred': d.idplan_credito} for d in documentos_por_plan]
    return jsonify(documentos=documentos)

@bp_creditos.route('/get_categorias_por_plan/<id>')
@check_session
def get_categorias_por_plan(id):
    categorias_por_plan = get_cats_por_plan(id)
    categorias = [{'id': c.id, 'nombre': c.nombre, 'idplan': c.idplan, 'idcat': c.idcategoria} for c in categorias_por_plan]
    return jsonify(categorias=categorias)

@bp_creditos.route('/add_documento_para_creditos', methods=['POST'])
@check_session
def add_documento_para_creditos():
    documentos = request.form.getlist('documentos')
    idplan_credito = request.form.get('idplandoc')
    limpiar_documentos_para_plan(idplan_credito)
    for doc in documentos:
        asignar_documento_para_plan(doc, idplan_credito)
    return redirect(url_for('creditos.config_cred'))

@bp_creditos.route('/add_categorias_para_creditos', methods=['POST'])
@check_session
def add_categorias_para_creditos():
    categorias = request.form.getlist('categorias')
    idplan_credito = request.form.get('idplancategoria')
    limpiar_categorias_para_plan(idplan_credito)
    for cat in categorias:
        asignar_categoria_para_plan(cat, idplan_credito)
    return redirect(url_for('creditos.config_cred'))


@bp_creditos.route('/add_plan_credito', methods=['POST'])
@check_session
@alertas_mensajes
def add_plan_credito():
    nombre = request.form['nombre']
    descripcion = request.form['descripcion']
    tasa_interes = request.form['tasa_interes']
    cuotas = request.form['cuotas']
    anticipo = request.form.get('anticipo', False)
    baja = date(1900, 1, 1)
    plan = procesar_plan_credito(nombre, descripcion, tasa_interes, cuotas, anticipo, baja)
    if plan:
        flash(f'Plan de crédito grabado: {plan.descripcion}')
        return redirect(url_for('creditos.config_cred'))
    else:
        flash(f'Error grabando plan de crédito: ', 'error')
        return redirect(url_for('creditos.config_cred'))
    
@bp_creditos.route('/add_documento_creditos', methods=['POST'])
@check_session
@alertas_mensajes
def add_documento_creditos():
    nombre = request.form['nombre_documento']
    documentos = procesar_documento_creditos(nombre)
    if documentos:
        flash(f'Documentos de crédito grabado: {documentos.nombre}')
        return redirect(url_for('creditos.config_cred'))
    else:
        flash('Error grabando documentos de crédito', 'error')
        return redirect(url_for('creditos.config_cred'))

@bp_creditos.route('/planes_para_cliente/<categoria>')
@check_session
def planes_para_cliente(categoria):
    planes = get_planes_creditos_categoria(categoria)
    planes = [{'id': p.id, 'nombre': p.nombre, 'tasa_interes': p.tasa_interes, 'cuotas': p.cuotas, 'anticipo': p.anticipo, 'garantes': p.garantes} for p in planes]
    return jsonify(success=True, planes=planes)

@bp_creditos.route('/add_estado_creditos', methods=['POST'])
@check_session
@alertas_mensajes
def add_estado_creditos():
    nombre = request.form['nombre_documento']
    descripcion = request.form['descripcion']
    estado = procesar_estado_creditos(nombre, descripcion)
    if estado:
        flash(f'Estado de crédito grabado: {estado.nombre}')
        return redirect(url_for('creditos.config_cred'))
    else:
        flash('Error grabando estado de crédito', 'error')
        return redirect(url_for('creditos.config_cred'))

@bp_creditos.route('/simulador_cred')
@check_session
@alertas_mensajes
def simulador_cred():
    planes = get_planes_creditos()
    datos_planes = [{'id': p.id, 'nombre': p.nombre, 'tasa_interes': p.tasa_interes, 'cuotas': p.cuotas, 'anticipo': p.anticipo} for p in planes]
    idPlanSeleccionado = request.args.get('idPlan', None)
    if idPlanSeleccionado:
        cuotas = request.args.get('cuotas', None)
        tasa_interes = request.args.get('tasa_interes', None)    
        monto_total = request.args.get('monto_total', None)
        anticipo = request.args.get('anticipo', None)
        if cuotas and tasa_interes and monto_total:
            monto_total = float(monto_total)
            cuotas = int(cuotas)
            tasa_interes = float(tasa_interes) / 100 #dividimos la tasa mensual en 100 para expresarlo como porcentage
            anticipo = anticipo == "True"
            cronograma, cuota = generar_cronograma_frances(monto_total, tasa_interes, cuotas)
            requisitos = get_requisitos(idPlanSeleccionado)
            return render_template('simulador-creditos.html', datos_planes=datos_planes, cronograma=cronograma, cuota=cuota, requisitos=requisitos, monto_total=monto_total, alertas=g.alertas, cantidadAlertas=g.cantidadAlertas, mensajes=g.mensajes, cantidadMensajes=g.cantidadMensajes)
    return render_template('simulador-creditos.html', datos_planes=datos_planes, alertas=g.alertas, cantidadAlertas=g.cantidadAlertas, mensajes=g.mensajes, cantidadMensajes=g.cantidadMensajes)

@bp_creditos.route('/generar_cuotas')
@check_session
def generar_cuotas():
    cuotas = request.args.get('cuotas', None)
    tasa_interes = request.args.get('tasa_interes', None)    
    monto_total = request.args.get('monto_total', None)
    cuotas = int(cuotas)
    tasa_interes = float(tasa_interes) / 100
    monto_total = float(monto_total)
    cronograma, cuota = generar_cronograma_frances(monto_total, tasa_interes, cuotas)
    return jsonify(cronograma=cronograma, cuota=cuota)

    

@bp_creditos.route('/otorgamiento')
@check_session
@alertas_mensajes
def otorgamiento():
    cliente = []
    credito = []
    fecha_solicitud = date.today()
    return render_template('otorgamiento.html', cliente=cliente, credito=credito, fecha_solicitud=fecha_solicitud, alertas=g.alertas, cantidadAlertas=g.cantidadAlertas, mensajes=g.mensajes, cantidadMensajes=g.cantidadMensajes)

@bp_creditos.route('/ver_credito/<id_credito>')
@check_session
@alertas_mensajes
def ver_credito(id_credito):
    # Aquí podrías cargar los datos del crédito específico utilizando el ID
    credito, garantes, documentos, cuotas_generadas = get_credito_by_id(id_credito)
    if not credito:
        flash('Crédito no encontrado', 'error')
        return redirect(url_for('creditos.otorgamiento'))
    planesCategorias = get_planes_creditos_categoria(credito.idcategoria)
    print(f"los documentos del crédito son: {documentos}")
    return render_template('ver-credito.html', credito=credito, garantes=garantes, documentos=documentos, cuotas_generadas=cuotas_generadas, planesCategorias=planesCategorias, alertas=g.alertas, cantidadAlertas=g.cantidadAlertas, mensajes=g.mensajes, cantidadMensajes=g.cantidadMensajes)

@bp_creditos.route('/generar_credito', methods=['POST'])
@check_session
@alertas_mensajes
def generar_credito():
    
    formulario = request.form
    archivos = request.files
    
    idcredito, mensaje = generar_credito_cliente(formulario, archivos)
    if not idcredito:
        flash(f'Error al generar el crédito: {mensaje}', 'error')
        return redirect(url_for('creditos.otorgamiento'))
    flash(f'El crédito ha sido generado con éxito: {idcredito}', 'success')
    return redirect(url_for('creditos.otorgamiento'))
    
@bp_creditos.route('/procesar_estado_credito', methods=['POST'])
@check_session
@alertas_mensajes
def procesar_estado_credito():
        
    idcredito = request.form.get('idcredito')
    estado = request.form.get('estado')
    idplan = request.form.get('idplan')
    monto_total = request.form.get('monto_total')
    tasa_interes = request.form.get('tasa_interes')
    cuotas = request.form.get('cuotas')
    observaciones = request.form.get('observaciones')
    if estado == '3':  # Aprobado
        cronograma, cuota = generar_cronograma_frances(float(monto_total), float(tasa_interes)/100, int(cuotas))
        cuotarGeneradas = grabar_cuotas(idcredito, idplan, cronograma)
        if not cuotarGeneradas:
            flash('Error al grabar las cuotas del crédito', 'error')

templates/creditos/lst-estados-creditos.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Listado de créditos {{ titulo }}</h1>
        </div>
    </div>
    <div class="row justify-content-center align-items-center">
        <div class="col-8">
            <div class="card m-3">
                <h5 class="px-5 pt-2">Periodo</h5>
                <div class="card-body">
                    <form action="{{ url_for(accion) }}" method="GET">
                        <div class="row justify-content-md-center">
                            <div class="col-md-3">
                                <label for="desde">Desde</label>
                                <input type="date" name="desde" id="desde" class="form-control" value="{{ desde }}">
                            </div>
                            <div class="col-md-3">
                                <label for="hasta">Hasta</label>
                                <input type="date" name="hasta" id="hasta" class="form-control" value="{{ hasta }}">
                            </div>    
                            <div class="col-md-2 m-4">
                                <button type="submit" class="btn btn-primario">Buscar</button>
                            </div>    
                        </div>
                    </form>
                </div>    
            </div>
        </div>    
    </div>
    <div class="card">
        <div class="card-body">
            <table class="table table-dark">
                <thead>
                    <tr>                    
                        <th scope="col">ID</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Fecha de solicitud</th>
                        <th scope="col">Plan</th>
                        <th scope="col">Monto</th>
                        <th scope="col">Estado</th>
                        <th scope="col">Acciones</th>
                    </tr>
                    
                </thead>
                <tbody>
                    {% for credito in creditos %}
                        <tr class="table table-light">
                            <td scope="row">{{ credito.id }}</td>
                            <td>{{ credito.cliente }}</td>
                            <td>{{ credito.fecha_solicitud }}</td>
                            <td>{{ credito.plan }}</td>
                            <td>{{ "{:,.2f}".format(credito.monto_total) }}</td>
                            <td>{{ credito.estado }}</td>
                            <td>
                               <a class="btn btn-primario" href="{{ url_for('creditos.ver_credito', id_credito=credito.id) }}">Ver</a> 
                            </td>
                        </tr>    
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>    

{% endblock %}

templates/creditos/lst-vencimiento-cuotas.html
{% extends "base.html" %}

{% block aditional_css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='vendor/datatable/dataTables.dataTables.css')}}">
{% endblock %}

{% block body %}
    <h2 class="m-3">Venciminetos de cuotas de créditos</h2>
    
    <div class="row justify-content-center align-items-center">
        <div class="col-8">
            <div class="card m-3">
                <h5 class="px-5 pt-2">Periodo</h5>
                <div class="card-body">
                    <form action="" method="post">
                        <div class="row justify-content-md-center">
                            <div class="col-md-3">
                                <label for="desde">Desde</label>
                                <input type="date" name="desde" id="desde" class="form-control" value="{{ desde }}">
                            </div>
                            <div class="col-md-3">
                                <label for="hasta">Hasta</label>
                                <input type="date" name="hasta" id="hasta" class="form-control" value="{{ hasta }}">
                            </div>    
                            <div class="col-md-2 m-4">
                                <button type="submit" class="btn btn-primario">Buscar</button>
                            </div>    
                        </div>
                    </form>
                </div>    
            </div>
        </div>    
    </div>
    
    <div class="row justify-content-center align-items-center">
        <div class="col-10">
            <div class="table-responsive m-3" >
                <table class="table display table-striped table-hover table-borderless align-middle" id="dataTable" >
                    <thead class="table-dark">
                        <tr>
                            <th width="7%">Crédito</th>
                            <th width="5%">N° Cuota</th>
                            <th>Cliente</th>
                            <th width="5%">Vencimiento</th>
                            <th>Cuota</th>
                            <th width="5%">Dias mora</th>
                            <th>Interes</th>
                            <th>Total</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody class="table-group-divider">
                        {% for cuota in cuotas %}        
                            <tr class="table-light">
                                {% if cuota.dias_mora == 0 %}
                                    <td scope="row">{{ cuota.idcredito }}</td>
                                    <td>{{ cuota.numero_cuota }}</td>
                                    <td>{{ cuota.nombre_cliente }}</td>
                                    <td>{{ cuota.fecha_vencimiento }}</td>
                                    <td style="text-align:center">{{ "${:,.2f}".format(cuota.monto) }}</td>
                                    <td style="text-align:center">{{ cuota.dias_mora }}</td>
                                    <td style="text-align:center">{{ "${:,.2f}".format(cuota.interes) }}</td>
                                    <td style="text-align:center">{{ "${:,.2f}".format(cuota.total_a_pagar) }}</td>
                                {% else %}
                                    <td scope="row" style="color: red">{{ cuota.idcredito }}</td>
                                    <td style="color: red">{{ cuota.numero_cuota }}</td>
                                    <td style="color: red">{{ cuota.nombre_cliente }}</td>
                                    <td style="color: red">{{ cuota.fecha_vencimiento }}</td>
                                    <td style="text-align:center; color: red">{{ "${:,.2f}".format(cuota.monto) }}</td>
                                    <td style="text-align:center; color: red">{{ cuota.dias_mora }}</td>
                                    <td style="text-align:center; color: red">{{ "${:,.2f}".format(cuota.interes) }}</td>
                                    <td style="text-align:center; color: red">{{ "${:,.2f}".format(cuota.total_a_pagar) }}</td>
                                {% endif %}
                                <td>
                                    <a href="{{ url_for('creditos.seleccionar_cuota', idcliente=cuota.idcliente, nom_cliente=cuota.nombre_cliente) }}" class="btn btn-secundario">Cobrar</a>
                                    <a href="{{ url_for('creditos.ver_credito', id_credito=cuota.idcredito) }}" class="btn btn-primario">Ver crédito</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>
                        
                    </tfoot>
                </table>
            </div>
        </div>    
    </div>

    <script src="/static/vendor/datatable/jquery-3.7.1.js"></script>
    <script src="/static/vendor/datatable/datatables.js"></script>
    <script src="/static/js/dataTables.js"></script>
    
{% endblock %}

templates/creditos/simulador-creditos.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <h3>Simulador de crédito</h3>
    <div class="card">
        <div class="card-body">
            <h6>Ingreso de Planes de crédito</h6>
            <form action="{{ url_for('creditos.simulador_cred') }}" method="get">
                <div class="mb-3"> 
                    <div class="row">
                        <div class="col-md-3">
                            <label for="nombre">Nombre</label>
                            <select class="form-control" name="idPlan" id="idPlan">
                                <option value="">Seleccione un plan</option>
                                {% for dato in datos_planes %}
                                    <option value="{{ dato.id }}">{{ dato.nombre }}</option>
                                {% endfor %}
                            </select>
                        </div>   
                        <div class="col-md-3">
                            <label for="cuotas">Cuotas</label>
                            <input class="form-control" type="number" step="1" name="cuotas" id="cuotas" placeholder="Cantidad de cuotas" max="1">
                        </div>
                        <div class="col-md-3">
                            <label for="tasa_interes">Tasa de interés</label>
                            <input class="form-control" type="number" step="0.01" name="tasa_interes" id="tasa_interes" placeholder="Tasa de interés">
                        </div>    
                        <div class="col-md-3">
                            <input class="form-check-input" type="checkbox" id="anticipo" name="anticipo" checked>
                            <label for="anticipo" class="form-check-label ml-5">Anticipo</label>
                        </div> 
                    </div>    
                    <div class="row">
                        <div class="col-md-4">
                            <label for="monto_total">Monto del crédito</label>
                            <input class="form-control " type="number" step="0.01" name="monto_total" id="monto_total" placeholder="Monto del crédito">
                        </div>    
                        
                    </div>
                    
                </div>
                <button class="btn btn-exito" type="submit">Calcular</button>
            </form>    
        </div>
    </div>
    <div class="card mt-3">
        <div class="card-title">
            <h5 class="mt-3 ml-3">Detalles del crédito</h5>
            {% if monto_total %}
                <h4 class="ml-3">Monto solicitado: <span class="precio-destacado"> {{ "${:,.2f}".format(monto_total) }} </span> -  Cuota mensual: <span class="precio-destacado"> {{ "${:,.2f}".format(cuota) }} </span> </h4>
            {% endif %}
            <h4 class="ml-3">Requisitos del plan</h4>
            <ul class="list-group list-group-flush ml-5">
                {% for requisito in requisitos %}
                    <li style="color: blue">{{ requisito.nombre }} </li>
                {% endfor %}
            </ul>
        </div>
        <div class="card-body">
            <div class="table-responsive">
            <table class="table table-dark">
                <thead>
                    <tr>
                        <th scope="col"># Cuota</th>
                        <th scope="col">Cuota</th>
                        <th scope="col">Interes</th>
                        <th scope="col">Capital</th>
                        <th scope="col">Saldo</th>
                    </tr>
                </thead>
                <tbody >
                    {% for cuota in cronograma %}
                        <tr class="table table-light">
                            <td scope="row">{{ cuota.nro_cuota }}</td>
                            <td scope="row">{{ "${:,.2f}".format(cuota.cuota) }}</td>
                            <td scope="row">{{ "${:,.2f}".format(cuota.interes) }}</td>
                            <td scope="row">{{ "${:,.2f}".format(cuota.capital) }}</td>
                            <td scope="row">{{ "${:,.2f}".format(cuota.saldo) }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            </div>
        </div>    
        <div class="card-footer">
            <a href="{{ url_for('creditos.otorgamiento') }}" class="btn btn-exito">Solicitar crédito</a>
        </div>
    </div>
</div>    
    
<script>
    const datos_plan = {{ datos_planes | tojson }};
    document.getElementById("idPlan").addEventListener("change", function (event) {
        const idPlan = event.target.value;
        if (idPlan) {
            let planSelecionado = 0;
            for (let i = 0; i < datos_plan.length; i++) {
                if (datos_plan[i].id == idPlan) {
                    planSelecionado = i;
                    break;
                }
            }
            let cuotas = datos_plan[planSelecionado].cuotas;
            let inputCuotas = document.getElementById("cuotas")
            inputCuotas.value = cuotas;
            inputCuotas.max = cuotas;
            let tasa_interes = datos_plan[planSelecionado].tasa_interes;
            let inputTasa_interes = document.getElementById("tasa_interes")
            inputTasa_interes.value = tasa_interes;
            let anticipo = datos_plan[planSelecionado].anticipo;
            let inputAnticipo = document.getElementById("anticipo")
            inputAnticipo.checked = anticipo == "True";
        }
    });
</script>

{% endblock %}